version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/main" # Location of package manifests
    schedule:
      interval: "daily"
      time: "21:30"
      timezone: "UTC"
    allow:
      - dependency-type: "direct"
      - dependency-type: "production"
    target-branch: "component-updates"
    versioning-strategy: "increase-if-necessary"
