# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/main" # Location of package manifests
    schedule:
      interval: "daily"
      time: "21:50"
      timezone: "UTC"
  - package-ecosystem: "bundler"
    directory: "/main"
    schedule:
      interval: "daily"
      time: "18:50"
      timezone: "America/Los_Angeles"
  - package-ecosystem: "composer"
    directory: "/main"
    schedule:
      interval: "daily"
      time: "21:50"
      timezone: "UTC"
  - package-ecosystem: "devcontainers"
    directory: "/main"
    schedule:
      interval: "daily"
      time: "21:50"
      timezone: "UTC"
  - package-ecosystem: "maven"
    directory: "/main"
    schedule:
      interval: "daily"
      time: "21:50"
      timezone: "UTC"
  - package-ecosystem: "mix"
    directory: "/main"
    schedule:
      interval: "daily"
      time: "21:50"
      timezone: "UTC"
  - package-ecosystem: "cargo"
    directory: "/main"
    schedule:
      interval: "daily"
      time: "21:50"
      timezone: "UTC"
  - package-ecosystem: "gradle"
    directory: "/main"
    schedule:
      interval: "daily"
      time: "21:50"
      timezone: "UTC"
  - package-ecosystem: "nuget"
    directory: "/main"
    schedule:
      interval: "daily"
      time: "21:50"
      timezone: "UTC"
  - package-ecosystem: "gomod"
    directory: "/main"
    schedule:
      interval: "daily"
      time: "21:50"
      timezone: "UTC"
  - package-ecosystem: "docker"
    directory: "/main"
    schedule:
      interval: "daily"
      time: "21:50"
      timezone: "UTC"
  - package-ecosystem: "elm"
    directory: "/main"
    schedule:
      interval: "daily"
      time: "21:50"
      timezone: "UTC"
  - package-ecosystem: "gitsubmodule"
    directory: "/main"
    schedule:
      interval: "daily"
      time: "21:50"
      timezone: "UTC"
  - package-ecosystem: "github-actions"
    directory: "/main"
    schedule:
      interval: "daily"
      time: "21:50"
      timezone: "UTC"
  - package-ecosystem: "pip"
    directory: "/main"
    schedule:
      interval: "daily"
      time: "21:50"
      timezone: "UTC"
  - package-ecosystem: "terraform"
    directory: "/main"
    schedule:
      interval: "daily"
      time: "21:50"
      timezone: "UTC"
  - package-ecosystem: "pub"
    directory: "/main"
    schedule:
      interval: "daily"
      time: "21:50"
      timezone: "UTC"
  - package-ecosystem: "swift"
    directory: "/main"
    schedule:
      interval: "daily"
      time: "21:50"
      timezone: "UTC"
    allow:
      - dependency-type: "direct"
      - dependency-type: "production"
    target-branch: "component-updates"
    versions: ["1.x", "2.x"]
