version: 1
updates:
  - package-ecosystem: "pip"
    directory: "/main"  # Répertoire principal contenant le fichier requirements.txt
    schedule:
      interval: "daily"  # Met à jour les dépendances quotidiennement
    target-branch: "main"  # Branche où les mises à jour seront appliquées

  - package-ecosystem: "pip"
    directory: "/subdir1"  # Répertoire secondaire 1 contenant un fichier requirements.txt
    schedule:
      interval: "weekly"  # Met à jour les dépendances hebdomadairement
    target-branch: "main"  # Branche où les mises à jour seront appliquées

  - package-ecosystem: "pip"
    directory: "/subdir2"  # Répertoire secondaire 2 contenant un fichier requirements.txt
    schedule:
      interval: "monthly"  # Met à jour les dépendances mensuellement
    target-branch: "main"  # Branche où les mises à jour seront appliquées
