version: 2
updates:
  - package-ecosystem: "pip" # Indique que nous utilisons pip pour la gestion des dépendances
    directory: "/" # Le répertoire où se trouvent les fichiers de configuration des dépendances
    schedule:
      interval: "daily" # Vérifier les mises à jour tous les jours
    ignore:
      - dependency-name: "tensorflow" # Exemple d'ignorance d'une dépendance spécifique
        versions: ["<2.0.0"] # Ignorer les mises à jour pour les versions inférieures à 2.0.0
      - dependency-name: "cirq" # Exemple d'ignorance d'une autre dépendance
        versions: ["<1.0.0"]

  - package-ecosystem: "pip" # Indique que nous utilisons pip pour la gestion des dépendances
    directory: "/" # Le répertoire où se trouvent les fichiers de configuration des dépendances
    schedule:
      interval: "weekly" # Vérifier les mises à jour chaque semaine
    ignore:
      - dependency-name: "numpy" # Exemple d'ignorance d'une dépendance spécifique
        versions: ["<1.25.0"]
