version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/main" # Chemin vers le manifeste des packages
    schedule:
      interval: "daily" # Intervalle de mise à jour
      time: "21:30" # Heure de mise à jour
      timezone: "UTC" # Fuseau horaire
    allow:
      - dependency-type: "direct" # Met à jour les dépendances directes
      - dependency-type: "production" # Met à jour les dépendances en production
    target-branch: "component-updates" # Branche cible pour les mises à jour
    versioning-strategy: "increase-if-necessary" # Stratégie de versioning
