# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "Tensorflow,  npm, bundler, composer, devcontainers, maven, mix, cargo, gradle, nuget, gomod, docker, elm, gitsubmodule, github-actions, pip, terraform, pub, swift" # See documentation for possible values
    directory: "/main" # Location of package manifests
    schedule:
    interval: "daily"
    time: "21:30"
    timezone: "UTC"
    schedule:
    interval: "daily"
    time: "18:30"
    timezone: "America/Los_Angeles"
    Allow:
      Depedency-type: Direct
      Depedency-type: Production #only correction, don't add more depedency
      Target-branch: "component-updates"
      versioning-strategy: increase-if-necessary
      name: "Tensorflow, npm, bundler, composer, devcontainers, maven, mix, cargo, gradle, nuget, gomod, docker, elm, gitsubmodule, github-actions, pip, terraform, pub, swift"
        # For Express, ignore all Dependabot updates for version 4 and 5
      versions: ["4.x", "5.x", "6.x", "7.x", "8.x", "9.x", "10.x", "11.x"]
