# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
    directory: "/main" # Location of package manifests
    schedule:
    interval: "daily"
    time: "21:30"
    timezone: "UTC"
    schedule:
    interval: "daily"
    time: "18:30"
    timezone: "America/Los_Angeles"
    Allow:
    - package-ecosystem: "npm, bundler, composer, devcontainers, maven, mix, cargo, gradle, nuget, gomod, docker, elm, gitsubmodule, github-actions, pip, terraform, pub, swift"
      Depedency-type: Direct
      Depedency-type: Production #only correction, don't add more depedency
      Target-branch: "component-updates"
      versioning-strategy: increase-if-necessary
      versions: ["4.x", "5.x"]
